sudo: required

language: python

install:
  - ./test/install_travis_env.sh

script:
  # can't rely on "/usr/bin/env python" for some reason
  - /usr/bin/python ./test/test.py cp2k@localhost

git:
  depth: 3
